apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicddemoapp1991
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicddemoapp1991
  template:
    metadata:
      labels:
        app: cicddemoapp1991
    spec:
      containers:
      - name: cicddemoapp1991
        image: cicddemoregistry1991.azurecr.io/cicddemoapp1991:v1
        ports:
        - containerPort: 80