name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Tests
        working-directory: ./backend
        run: npx jest

      - name: Log in to Azure Container Registry using Docker
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login cicddemoregistry1991.azurecr.io --username "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build and Push to Azure Container Registry
        run: |
          docker build -t cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }} ./backend
          docker push cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubernetes context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: MyUSAKSCluster
          resource-group: MyUSResourceGroup

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/cicddemoapp1991 cicddemoapp1991=cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }}
          kubectl rollout status deployment/cicddemoapp1991
