name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Tests
        working-directory: ./backend
        run: npx jest

      - name: Log in to Azure Container Registry (ACR)
        run: az acr login --name cicddemoregistry1991

      - name: Build and Push to Azure Container Registry
        run: |
          docker build -t cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }} ./backend
          docker push cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }}

      - name: Log in and Push to Docker Hub (if credentials are set)
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker tag cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }} pillowcasestudies/backend-app
          docker push pillowcasestudies/backend-app