name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Tests
        working-directory: ./backend
        run: npm test

      - name: Log in to Azure Container Registry (ACR)
        run: az acr login --name cicddemoregistry1991
        env:
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}

      - name: Build and Push to Azure Container Registry
        run: |
          docker build -t cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }} ./backend
          docker push cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }}

      # Optional: Push to Docker Hub if needed
      - name: Push Docker Image to Docker Hub
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }} pillowcasestudies/backend-app
          docker push pillowcasestudies/backend-app