name: Deploy to Azure

on:
  push:
    branches:
      - main  # Change if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          docker build -t cicddemoregistry1991.azurecr.io/cicddemoapp1991:v1 ./backend
          echo "${{ secrets.ACR_PASSWORD }}" | docker login cicddemoregistry1991.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push cicddemoregistry1991.azurecr.io/cicddemoapp1991:v1

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "CiCdDemoApp1991"
          images: "cicddemoregistry1991.azurecr.io/cicddemoapp1991:v1"