name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry using Docker
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login cicddemoregistry1991.azurecr.io --username "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }} -f ./backend/Dockerfile ./backend
          docker push cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group MyResourceGroup --name MyUSAKSCluster --overwrite-existing

      - name: Check if deployment exists
        run: |
          kubectl get deployment cicddemoapp1991 || echo "Deployment not found, creating a new one"

      - name: Deploy to AKS (Update Deployment Image)
        run: |
          kubectl set image deployment/cicddemoapp1991 cicddemoapp1991=cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }}
          kubectl rollout status deployment/cicddemoapp1991