name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure credentials stored in GitHub secrets

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name cicddemoregistry1991

      - name: Build and push Docker image
        run: |
          docker build -t cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }} -f Dockerfile .
          docker push cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }}

      - name: Set up Kubernetes kubeconfig
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}  # Your Kubeconfig stored in GitHub secretss

      - name: Check if deployment exists
        run: |
          kubectl get deployment cicddemoapp1991 || echo "Deployment not found, creating a new one"

      - name: Deploy to AKS (Update Deployment Image)
        run: |
          kubectl set image deployment/cicddemoapp1991 cicddemoapp1991=cicddemoregistry1991.azurecr.io/cicddemoapp1991:${{ github.sha }}
          kubectl rollout status deployment/cicddemoapp1991